In [1]:
from datasets import load_dataset

dataset = load_dataset("tatsu-lab/alpaca")
# alpaca because we want our model to learn how to ans correctly and its data size is also good
dataset

c:\AlignLab\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

DatasetDict({
    train: Dataset({
        features: ['instruction', 'input', 'output', 'text'],
        num_rows: 52002
    })
})

In [2]:
import pandas as pd

df = dataset["train"].to_pandas()

df.head(10)

,instruction,input,output,text
0,Give three tips for staying healthy.,,1.Eat a balanced diet and make sure to include...,Below is an instruction that describes a task....
1,What are the three primary colors?,,"The three primary colors are red, blue, and ye...",Below is an instruction that describes a task....
2,Describe the structure of an atom.,,"An atom is made up of a nucleus, which contain...",Below is an instruction that describes a task....
3,How can we reduce air pollution?,,There are a number of ways to reduce air pollu...,Below is an instruction that describes a task....
4,Describe a time when you had to make a difficu...,,I had to make a difficult decision when I was ...,Below is an instruction that describes a task....
5,Identify the odd one out.,"Twitter, Instagram, Telegram",Telegram,"Below is an instruction that describes a task,..."
6,Explain why the following fraction is equivale...,4/16,The fraction 4/16 is equivalent to 1/4 because...,"Below is an instruction that describes a task,..."
7,Write a short story in third person narration ...,,John was at a crossroads in his life. He had j...,Below is an instruction that describes a task....
8,Render a 3D model of a house,,<nooutput> This type of instruction cannot be ...,Below is an instruction that describes a task....
9,Evaluate this sentence for spelling and gramma...,He finnished his meal and left the resturant,He finished his meal and left the restaurant.,"Below is an instruction that describes a task,..."

In [3]:
df.shape

(52002, 4)

In [4]:
df.columns

Index(['instruction', 'input', 'output', 'text'], dtype='str')

In [5]:
df.sample(5, random_state=42)[["instruction", "input", "output","text"]]

,instruction,input,output,text
38199,Describe the character of the protagonist in t...,Game of Thrones,The protagonist of Game of Thrones is the long...,"Below is an instruction that describes a task,..."
20985,Construct a poem that describes the beauty of ...,,"The setting sun paints a scene of beauty, \nA ...",Below is an instruction that describes a task....
13643,Describe the effects of exponential growth.,,Exponential growth is a phenomenon in which an...,Below is an instruction that describes a task....
11300,Imagine a future world where robots and humans...,,"In the future, robots and humans will exist to...",Below is an instruction that describes a task....
32153,Create a list of three benefits of cloud compu...,,"1. Cost savings, as most cloud computing servi...",Below is an instruction that describes a task....

In [6]:
df["input"].eq("").sum()

np.int64(31323)

In [7]:
df["instruction"].duplicated().sum()
# how many duplicates avilable

np.int64(0)

In [8]:
df["output"].str.len().describe()

count    52002.000000
mean       270.312334
std        275.025960
min          0.000000
25%         53.000000
50%        185.000000
75%        423.000000
max       4181.000000
Name: output, dtype: float64

In [9]:
# longest example 
df.loc[df["output"].str.len().nlargest(5).index, ["instruction", "output"]]

,instruction,output
6285,Generate a 10 annotated bibliography given the...,"1. Anderson, B. (2012). Climate Change and Hum..."
45289,Explain a common misconception about your topic.,A common misconception about AI augmentation i...
15102,Explain how the Gini index is calculated.,The Gini index is a measure of economic inequa...
15908,Write four articles on the topic of cryptocurr...,Article #1\nWhat Is Cryptocurrency?\n \nCrypto...
26999,Generate an essay of at least 500 words that a...,Artificial intelligence (AI) has been a hot to...

In [10]:
df[df["output"].str.strip().eq("")][["instruction", "input", "output"]]

,instruction,input,output
284,Standardize the following date to the ISO 8601...,"July 26th, 2021",
1223,Create an illustration for the following text.,Gun violence in the United States can result i...,
1347,Convert 20 inches to centimetres,,
1736,Calculate the sum of all the digits in the giv...,18047,
7723,Use the given data to create a bar chart,Region | Population\nNorth | 2000\nCent...,
9038,Convert the dates into ISO 8601 format,"November 25, 2020",
11263,Estimate the sum of (4^4+2^2+9),,
11355,Write a simple math equation to calculate 10% ...,,
11471,"Given a paragraph, summarize it in three sente...",The year 2020 has been an incredibly difficult...,
14634,Convert 20 minutes into seconds.,,
15015,"Given a passage, please output the number of w...","Every once in a while, it is important to reac...",
23488,Calculate 20% of 200.,,
24322,Calculate the area of the following shape in s...,rectangle of size 4 cm x 5 cm,
24449,Create a flow chart to explain the working of ...,,
24541,Generate a random example of an IPv4 address.,,
25034,"Given a set of shoe size, add up the total size","Size 4, Size 7, Size 9",
28250,Give the result of the following multiplication.,25 x 8,
30605,Create a movie poster for this movie.,Our Space Adventure,
31653,Convert 20 milliliters to tablespoons,,
32425,Determine the next two numbers in the followin...,,
35802,Construct a timeline to show the development o...,,
44274,"Given the following list of items, find their ...","2, 4, 6, 8",
45538,"What year was the movie ""La La Land"" released?",,
46258,Calculate the age of a person who was born on ...,No input,
46811,Compress the text to half of its original leng...,The year 2020 has been difficult for many peop...,
49181,Retrieve the following data from the World Ban...,,
49248,Make a projection of the expected income for t...,"Income in 2019: $50,000\nIncome increase rate ...",
51388,Generate an example of a bar chart to visually...,"Number of cats (2,5,3,1,4)",

In [11]:
df[df["output"].isna() | df["output"].str.strip().eq("")][
    ["instruction", "input", "output"]
]

,instruction,input,output
284,Standardize the following date to the ISO 8601...,"July 26th, 2021",
1223,Create an illustration for the following text.,Gun violence in the United States can result i...,
1347,Convert 20 inches to centimetres,,
1736,Calculate the sum of all the digits in the giv...,18047,
7723,Use the given data to create a bar chart,Region | Population\nNorth | 2000\nCent...,
9038,Convert the dates into ISO 8601 format,"November 25, 2020",
11263,Estimate the sum of (4^4+2^2+9),,
11355,Write a simple math equation to calculate 10% ...,,
11471,"Given a paragraph, summarize it in three sente...",The year 2020 has been an incredibly difficult...,
14634,Convert 20 minutes into seconds.,,
15015,"Given a passage, please output the number of w...","Every once in a while, it is important to reac...",
23488,Calculate 20% of 200.,,
24322,Calculate the area of the following shape in s...,rectangle of size 4 cm x 5 cm,
24449,Create a flow chart to explain the working of ...,,
24541,Generate a random example of an IPv4 address.,,
25034,"Given a set of shoe size, add up the total size","Size 4, Size 7, Size 9",
28250,Give the result of the following multiplication.,25 x 8,
30605,Create a movie poster for this movie.,Our Space Adventure,
31653,Convert 20 milliliters to tablespoons,,
32425,Determine the next two numbers in the followin...,,
35802,Construct a timeline to show the development o...,,
44274,"Given the following list of items, find their ...","2, 4, 6, 8",
45538,"What year was the movie ""La La Land"" released?",,
46258,Calculate the age of a person who was born on ...,No input,
46811,Compress the text to half of its original leng...,The year 2020 has been difficult for many peop...,
49181,Retrieve the following data from the World Ban...,,
49248,Make a projection of the expected income for t...,"Income in 2019: $50,000\nIncome increase rate ...",
51388,Generate an example of a bar chart to visually...,"Number of cats (2,5,3,1,4)",

In [12]:
print("Empty instruction:", df["instruction"].isna().sum())
print("Empty output:", df["output"].isna().sum())

print("Very short instructions:", (df["instruction"].str.strip().str.len() < 5).sum())
print("Very short outputs:", (df["output"].str.strip().str.len() < 5).sum())

Empty instruction: 0
Empty output: 0
Very short instructions: 0
Very short outputs: 912

In [13]:
print("NaN outputs:", df["output"].isna().sum())
print("Empty string outputs:", df["output"].str.strip().eq("").sum())

NaN outputs: 0
Empty string outputs: 28

In [14]:
df[df["output"].str.strip().str.len() < 5][
    ["instruction", "input", "output"]
].head(20)

,instruction,input,output
81,Classify the following incident as a breach of...,Using a school laptop for personal use,1
154,"Given an array of integers, return the first r...","arr = [3, 6, 7, 1, 4, 6, 7]",6
155,Find the two non-repeating elements in an arra...,"arr = [2, 3, 7, 9, 11, 2, 3, 11]","7, 9"
157,Find the maximum profit that can be earned fro...,"arr = [100, 180, 260, 310, 40, 535, 695]",865
180,"Classify the given input as either a poem, sto...","Once upon a midnight dreary, while I pondered,...",Poem
211,Convert the following hexadecimal number to oc...,DB,333
226,"Generate the third term in the sequence 2, 5, ...",,18
266,"Given a sequence of numbers, calculate the ave...","1, 2, 3, 4, 5",3.0
270,"Given the following data, What is the median s...","7, 9, 13, 2, 8",8
284,Standardize the following date to the ISO 8601...,"July 26th, 2021",
287,Compute the following expression.,2^3 + 3^2,11
399,Compute the sum of the following numbers.,"5, 10, 20",35
403,Find the sum of the numbers 6 and 12.,6 + 12,18.
410,Find the greatest common factor of 12 and 18.,12 & 18,6.
491,Provide the answer to the equation.,7 + 6,13
513,Answer this math problem.,12/8,1.5
521,Provide an example of an antonym for the word ...,,Sad
527,Evaluate the following expression: (6+2)*(2-2).,,8
682,Compute the area of triangle from the given 3 ...,"side1=3, side2=4, side3=5",6
686,Calculate the surface area of a cube from the ...,a=4,64

In [15]:
# ye small jarur h pr shi hai so hatane ka mtlab nhi h

In [16]:
# removing blank strings.
df = df[
    df["output"].notna() &
    df["output"].str.strip().ne("")
].copy()

print("Rows after cleaning:", len(df))

Rows after cleaning: 51974

In [ ]:
#Formatting function
# ### Instruction:
# Translate this sentence.
# ### Input:
# Hello world.
# ### Response:
# Hola mundo.

In [ ]:
def format_example(row):
    instruction = row["instruction"].strip()
    input_text = row["input"].strip()
    output = row["output"].strip()

    if input_text:
        prompt = f"""### Instruction:
{instruction}

### Input:
{input_text}

### Response:
{output}"""
    else:
        prompt = f"""### Instruction:
{instruction}

### Response:
{output}"""

    return prompt

# nya col. bna k store krega
df["formatted_text"] = df.apply(format_example, axis=1)
# printing new col
print(df["formatted_text"].iloc[0])

### Instruction:
Give three tips for staying healthy.

### Response:
1.Eat a balanced diet and make sure to include plenty of fruits and vegetables.
2. Exercise regularly to keep your body active and strong.
3. Get enough sleep and maintain a consistent sleep schedule.

In [19]:
print(df["formatted_text"].head())

0    ### Instruction:\nGive three tips for staying ...
1    ### Instruction:\nWhat are the three primary c...
2    ### Instruction:\nDescribe the structure of an...
3    ### Instruction:\nHow can we reduce air pollut...
4    ### Instruction:\nDescribe a time when you had...
Name: formatted_text, dtype: str

In [20]:
df

,instruction,input,output,text,formatted_text
0,Give three tips for staying healthy.,,1.Eat a balanced diet and make sure to include...,Below is an instruction that describes a task....,### Instruction:\nGive three tips for staying ...
1,What are the three primary colors?,,"The three primary colors are red, blue, and ye...",Below is an instruction that describes a task....,### Instruction:\nWhat are the three primary c...
2,Describe the structure of an atom.,,"An atom is made up of a nucleus, which contain...",Below is an instruction that describes a task....,### Instruction:\nDescribe the structure of an...
3,How can we reduce air pollution?,,There are a number of ways to reduce air pollu...,Below is an instruction that describes a task....,### Instruction:\nHow can we reduce air pollut...
4,Describe a time when you had to make a difficu...,,I had to make a difficult decision when I was ...,Below is an instruction that describes a task....,### Instruction:\nDescribe a time when you had...
...,...,...,...,...,...
51997,Generate an example of what a resume should li...,,"Jean Tremaine\n1234 Main Street, Anytown, CA 9...",Below is an instruction that describes a task....,### Instruction:\nGenerate an example of what ...
51998,Arrange the items given below in the order to ...,"cake, me, eating",I eating cake.,"Below is an instruction that describes a task,...",### Instruction:\nArrange the items given belo...
51999,Write an introductory paragraph about a famous...,Michelle Obama,Michelle Obama is an inspirational woman who r...,"Below is an instruction that describes a task,...",### Instruction:\nWrite an introductory paragr...
52000,Generate a list of five things one should keep...,,1. Research potential opportunities and carefu...,Below is an instruction that describes a task....,### Instruction:\nGenerate a list of five thin...
52001,Analyze the given legal document and explain t...,The following is an excerpt from a contract be...,This legal document states that Company A has ...,"Below is an instruction that describes a task,...",### Instruction:\nAnalyze the given legal docu...

In [ ]:
# tokenizetion
#inspecting Pythia tokenizer
from transformers import AutoTokenizer

tokenizer=AutoTokenizer.from_pretrained(
    "EleutherAI/pythia-160m"
)

if tokenizer.pad_token is None:
    tokenizer.pad_token=tokenizer.eos_token

print("Vocabulary size:", tokenizer.vocab_size)
print("Tokenizer class:", tokenizer.__class__.__name__)
print("EOS token:", tokenizer.eos_token)
print("EOS token ID:", tokenizer.eos_token_id)
print("PAD token:", tokenizer.pad_token)
print("PAD token ID:", tokenizer.pad_token_id)

Vocabulary size: 50254
Tokenizer class: GPTNeoXTokenizer
EOS token: <|endoftext|>
EOS token ID: 0
PAD token: <|padding|>
PAD token ID: 1

In [ ]:
#tokenizeing 1 example
sample = df["formatted_text"].iloc[0]

encoded = tokenizer(
    sample,
    add_special_tokens=True
)

print("Original text:\n")
print(sample)

print("\nFirst 30 token IDs:")
print(encoded["input_ids"][:30])

print("\nTotal tokens:")
print(len(encoded["input_ids"]))

Original text:

### Instruction:
Give three tips for staying healthy.

### Response:
1.Eat a balanced diet and make sure to include plenty of fruits and vegetables.
2. Exercise regularly to keep your body active and strong.
3. Get enough sleep and maintain a consistent sleep schedule.

First 30 token IDs:
[4118, 41959, 27, 187, 19735, 1264, 12192, 323, 14596, 5875, 15, 187, 187, 4118, 19371, 27, 187, 18, 15, 38, 255, 247, 16645, 6196, 285, 1056, 2119, 281, 2486, 9828]

Total tokens:
63

In [23]:
#Token-length analysis 
token_lengths = df["formatted_text"].apply(
    lambda x: len(
        tokenizer(
            x,
            add_special_tokens=True
        )["input_ids"]
    )
)

print(token_lengths.describe())

count    51974.000000
mean        87.283526
std         57.325272
min         15.000000
25%         45.000000
50%         72.000000
75%        113.000000
max       1005.000000
Name: formatted_text, dtype: float64

In [ ]:
#cheacking how many examples are grater than 256/512/1024:
for limit in [128, 256, 512, 1024]:
    count = (token_lengths > limit).sum()
    percentage = (token_lengths > limit).mean() * 100

    print(
        f"{limit} tokens: "
        f"{count} examples "
        f"({percentage:.2f}%)"
    )
    #For example, if onlym0.5% examples are greater than 512,then 512 cab be a practical choice.

128 tokens: 9351 examples (17.99%)
256 tokens: 907 examples (1.75%)
512 tokens: 40 examples (0.08%)
1024 tokens: 0 examples (0.00%)

In [ ]:
#Agar MAX_LENGTH = 512:
#only 0.08%, 40 examples will be truncate.
# so for AlignLab 
# MAX_LENGTH = 512 .

In [26]:
#MAX_LENGTH lock
MAX_LENGTH = 512
print("MAX_LENGTH =", MAX_LENGTH)

MAX_LENGTH = 512

In [ ]:
# train test split
#90/10 split
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(
    df,
    test_size=0.10,
    random_state=42,
    shuffle=True
)

train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)

print("Total:", len(df))
print("Train:", len(train_df))
print("Validation:", len(val_df))
#random_state=42 se same random split reproduce.if dubara run kre to

Total: 51974
Train: 46776
Validation: 5198

In [29]:
print("Train shape:", train_df.shape)
print("Validation shape:", val_df.shape)

print("\nTrain example:")
print(train_df["formatted_text"].iloc[0])

print("\nValidation example:")
print(val_df["formatted_text"].iloc[0])

Train shape: (46776, 5)
Validation shape: (5198, 5)

Train example:
### Instruction:
Build an algorithm to recommend books to readers based on their preferences.

### Response:
An algorithm to recommend books to readers can be built using a collaborative filtering model. The model takes into account the ratings that users have given to particular books and the relationships between different user preferences to create a more personalised book recommendation system. The model also takes into account the characteristics of a book, such as its genre, author, or release date, to provide more accurate recommendations to the user.

Validation example:
### Instruction:
Select an appropriate Machine Learning algorithm for this problem.

### Input:
We would like to predict if someone is a regular customer of a restaurant based on their visit history and demographic information.

### Response:
The appropriate Machine Learning algorithm for this problem is logistic regression.

In [ ]:
# response-only masking ke liye hume prompt aur response ki boundary exactly pata honi chahiye.
# Isliye train aur validation ke liye ye function banayenge:
def prepare_sft_example(row):
    instruction = row["instruction"].strip()
    input_text = row["input"].strip()
    output = row["output"].strip()

    if input_text:
        prompt = (
            f"### Instruction:\n"
            f"{instruction}\n\n"
            f"### Input:\n"
            f"{input_text}\n\n"
            f"### Response:\n"
        )
    else:
        prompt = (
            f"### Instruction:\n"
            f"{instruction}\n\n"
            f"### Response:\n"
        )

    full_text = prompt + output

    return {
        "prompt": prompt,
        "response": output,
        "text": full_text
    }

In [ ]:
#Function apply
train_prepared = train_df.apply(
    prepare_sft_example,
    axis=1,
    result_type="expand"
)

val_prepared = val_df.apply(
    prepare_sft_example,
    axis=1,
    result_type="expand"
)

print(train_prepared.columns.tolist())
print(val_prepared.columns.tolist())

['prompt', 'response', 'text']
['prompt', 'response', 'text']

In [32]:
print(train_prepared.iloc[0])

prompt      ### Instruction:\nBuild an algorithm to recomm...
response    An algorithm to recommend books to readers can...
text        ### Instruction:\nBuild an algorithm to recomm...
Name: 0, dtype: str

In [33]:
#tokenization function
def tokenize_example(row):
    return tokenizer(
        row["text"],
        truncation=True,
        max_length=MAX_LENGTH,
        padding=False
    )

In [34]:
#single example test
test_tokens = tokenize_example(train_prepared.iloc[0])

print(test_tokens.keys())

print("\nInput IDs:")
print(test_tokens["input_ids"][:30])

print("\nAttention mask:")
print(test_tokens["attention_mask"][:30])

print("\nNumber of tokens:")
print(len(test_tokens["input_ids"]))

KeysView({'input_ids': [4118, 41959, 27, 187, 10987, 271, 5933, 281, 5583, 5098, 281, 10668, 1754, 327, 616, 17971, 15, 187, 187, 4118, 19371, 27, 187, 1145, 5933, 281, 5583, 5098, 281, 10668, 476, 320, 4270, 970, 247, 27549, 19690, 1566, 15, 380, 1566, 3936, 715, 2395, 253, 17503, 326, 4212, 452, 1677, 281, 1798, 5098, 285, 253, 7688, 875, 1027, 2608, 17971, 281, 2794, 247, 625, 3367, 1701, 1984, 17401, 985, 15, 380, 1566, 671, 3936, 715, 2395, 253, 5319, 273, 247, 1984, 13, 824, 347, 697, 19098, 13, 2488, 13, 390, 3727, 3522, 13, 281, 2085, 625, 7899, 12645, 281, 253, 2608, 15], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]})

Input IDs:
[4118, 41959, 27, 187, 10987, 271, 5933, 281, 5583, 5098, 281, 10668, 1754, 327, 616, 17971, 15, 187, 187, 4118, 19371, 27, 187, 1145, 5933, 281, 5583, 5098, 281, 10668]

Attention mask:
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

Number of tokens:
102

In [35]:
print(encoded.keys())

KeysView({'input_ids': [4118, 41959, 27, 187, 19735, 1264, 12192, 323, 14596, 5875, 15, 187, 187, 4118, 19371, 27, 187, 18, 15, 38, 255, 247, 16645, 6196, 285, 1056, 2119, 281, 2486, 9828, 273, 18098, 285, 15737, 15, 209, 187, 19, 15, 40626, 11719, 281, 1978, 634, 2133, 3939, 285, 2266, 15, 209, 187, 20, 15, 5057, 2217, 4600, 285, 6558, 247, 5185, 4600, 10130, 15], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]})

In [36]:
ids = test_tokens["input_ids"]

decoded_text = tokenizer.decode(ids)

print(decoded_text)

### Instruction:
Build an algorithm to recommend books to readers based on their preferences.

### Response:
An algorithm to recommend books to readers can be built using a collaborative filtering model. The model takes into account the ratings that users have given to particular books and the relationships between different user preferences to create a more personalised book recommendation system. The model also takes into account the characteristics of a book, such as its genre, author, or release date, to provide more accurate recommendations to the user.

In [40]:
#Labels
#Full tokenization + masking function
def tokenize_and_mask(row):
    prompt = row["prompt"]
    text = row["text"]

    full_tokens = tokenizer(
        text,
        truncation=True,
        max_length=MAX_LENGTH,
        padding=False
    )

    prompt_tokens = tokenizer(
        prompt,
        add_special_tokens=False,
        truncation=False
    )

    input_ids = full_tokens["input_ids"]
    attention_mask = full_tokens["attention_mask"]

    prompt_length = len(prompt_tokens["input_ids"])

    # If truncation removed the entire response,
    # this example provides no useful response loss.
    if prompt_length >= len(input_ids):
        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "labels": [-100] * len(input_ids)
        }

    labels = [-100] * len(input_ids)

    for i in range(prompt_length, len(input_ids)):
        labels[i] = input_ids[i]

    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels
    }

In [ ]:
#single example testing 
test_prepared = train_prepared.iloc[0]

test_result = tokenize_and_mask(test_prepared)

print("Input IDs:")
print(test_result["input_ids"])

print("\nLabels:")
print(test_result["labels"])

print("\nAttention mask:")
print(test_result["attention_mask"])

Input IDs:
[4118, 41959, 27, 187, 10987, 271, 5933, 281, 5583, 5098, 281, 10668, 1754, 327, 616, 17971, 15, 187, 187, 4118, 19371, 27, 187, 1145, 5933, 281, 5583, 5098, 281, 10668, 476, 320, 4270, 970, 247, 27549, 19690, 1566, 15, 380, 1566, 3936, 715, 2395, 253, 17503, 326, 4212, 452, 1677, 281, 1798, 5098, 285, 253, 7688, 875, 1027, 2608, 17971, 281, 2794, 247, 625, 3367, 1701, 1984, 17401, 985, 15, 380, 1566, 671, 3936, 715, 2395, 253, 5319, 273, 247, 1984, 13, 824, 347, 697, 19098, 13, 2488, 13, 390, 3727, 3522, 13, 281, 2085, 625, 7899, 12645, 281, 253, 2608, 15]

Labels:
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 1145, 5933, 281, 5583, 5098, 281, 10668, 476, 320, 4270, 970, 247, 27549, 19690, 1566, 15, 380, 1566, 3936, 715, 2395, 253, 17503, 326, 4212, 452, 1677, 281, 1798, 5098, 285, 253, 7688, 875, 1027, 2608, 17971, 281, 2794, 247, 625, 3367, 1701, 1984, 17401, 985, 15, 380, 1566, 671, 3936, 715, 2395, 253, 5319, 273, 247, 1984, 13, 824, 347, 697, 19098, 13, 2488, 13, 390, 3727, 3522, 13, 281, 2085, 625, 7899, 12645, 281, 253, 2608, 15]

Attention mask:
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [42]:
#Masking visually verify
for token_id, label in zip(
    test_result["input_ids"],
    test_result["labels"]
):
    token = tokenizer.decode([token_id])

    print(
        repr(token),
        "→",
        label
    )

'###' → -100
' Instruction' → -100
':' → -100
'\n' → -100
'Build' → -100
' an' → -100
' algorithm' → -100
' to' → -100
' recommend' → -100
' books' → -100
' to' → -100
' readers' → -100
' based' → -100
' on' → -100
' their' → -100
' preferences' → -100
'.' → -100
'\n' → -100
'\n' → -100
'###' → -100
' Response' → -100
':' → -100
'\n' → -100
'An' → 1145
' algorithm' → 5933
' to' → 281
' recommend' → 5583
' books' → 5098
' to' → 281
' readers' → 10668
' can' → 476
' be' → 320
' built' → 4270
' using' → 970
' a' → 247
' collaborative' → 27549
' filtering' → 19690
' model' → 1566
'.' → 15
' The' → 380
' model' → 1566
' takes' → 3936
' into' → 715
' account' → 2395
' the' → 253
' ratings' → 17503
' that' → 326
' users' → 4212
' have' → 452
' given' → 1677
' to' → 281
' particular' → 1798
' books' → 5098
' and' → 285
' the' → 253
' relationships' → 7688
' between' → 875
' different' → 1027
' user' → 2608
' preferences' → 17971
' to' → 281
' create' → 2794
' a' → 247
' more' → 625
' personal' → 3367
'ised' → 1701
' book' → 1984
' recommendation' → 17401
' system' → 985
'.' → 15
' The' → 380
' model' → 1566
' also' → 671
' takes' → 3936
' into' → 715
' account' → 2395
' the' → 253
' characteristics' → 5319
' of' → 273
' a' → 247
' book' → 1984
',' → 13
' such' → 824
' as' → 347
' its' → 697
' genre' → 19098
',' → 13
' author' → 2488
',' → 13
' or' → 390
' release' → 3727
' date' → 3522
',' → 13
' to' → 281
' provide' → 2085
' more' → 625
' accurate' → 7899
' recommendations' → 12645
' to' → 281
' the' → 253
' user' → 2608
'.' → 15

In [46]:
# whole train dataset ko tokenize
train_tokenized = train_prepared.apply(
    tokenize_and_mask,
    axis=1,
    result_type="expand"
)

val_tokenized = val_prepared.apply(
    tokenize_and_mask,
    axis=1,
    result_type="expand"
)

print("Train:", train_tokenized.shape)
print("Validation:", val_tokenized.shape)
print("\nColumns:")
print(train_tokenized.columns.tolist())

Train: (46776, 3)
Validation: (5198, 3)

Columns:
['input_ids', 'attention_mask', 'labels']

In [47]:
#Final sanity check

In [52]:
#shape test
print("\nColumns:")
print(train_tokenized.columns.tolist())
print("Train shape:", train_tokenized.shape)
print("Validation shape:", val_tokenized.shape)
#Sequence lengths verify
print("Train input lengths:")
print(train_tokenized["input_ids"].apply(len).describe())
print("\nTrain label lengths:")
print(train_tokenized["labels"].apply(len).describe())
print("\nTrain attention lengths:")
print(train_tokenized["attention_mask"].apply(len).describe())
#in teeno ka length distribution same hona chahiye.
#All-masked examples check
def is_all_masked(labels):
    return all(label == -100 for label in labels)
train_all_masked = train_tokenized["labels"].apply(is_all_masked).sum()
val_all_masked = val_tokenized["labels"].apply(is_all_masked).sum()
print("Train all-masked examples:", train_all_masked)
print("Validation all-masked examples:", val_all_masked)
#Response tokens kitne hain
def count_response_tokens(labels):
    return sum(label != -100 for label in labels)
response_lengths = train_tokenized["labels"].apply(count_response_tokens)
print(response_lengths.describe())

print("\n-------$------------------------------")
# print("\nFirst training example:")
# print(train_tokenized.iloc[0])
#token count:
print(
    "First example token count:",
    len(train_tokenized.iloc[0]["input_ids"])
)

print(
    "First example label count:",
    len(train_tokenized.iloc[0]["labels"])
)
# both length should be same

Columns:
['input_ids', 'attention_mask', 'labels']
Train shape: (46776, 3)
Validation shape: (5198, 3)
Train input lengths:
count    46776.000000
mean        87.180434
std         56.681492
min         15.000000
25%         45.000000
50%         72.000000
75%        113.000000
max        512.000000
Name: input_ids, dtype: float64

Train label lengths:
count    46776.000000
mean        87.180434
std         56.681492
min         15.000000
25%         45.000000
50%         72.000000
75%        113.000000
max        512.000000
Name: labels, dtype: float64

Train attention lengths:
count    46776.000000
mean        87.180434
std         56.681492
min         15.000000
25%         45.000000
50%         72.000000
75%        113.000000
max        512.000000
Name: attention_mask, dtype: float64
Train all-masked examples: 1
Validation all-masked examples: 0
count    46776.000000
mean        57.167500
std         56.645285
min          0.000000
25%         13.000000
50%         42.000000
75%         85.000000
max        497.000000
Name: labels, dtype: float64

-------$------------------------------
First example token count: 102
First example label count: 102

In [53]:
#Pandas → Hugging Face Dataset
from datasets import Dataset

train_dataset = Dataset.from_pandas(
    train_tokenized,
    preserve_index=False
)

val_dataset = Dataset.from_pandas(
    val_tokenized,
    preserve_index=False
)

print(train_dataset)
print(val_dataset)

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 46776
})
Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 5198
})

In [ ]:
# why conversion?

# now:pandas DataFrame mein data hai.
# Training ke liye Hugging Face ecosystem ka:datasets.Dataset zyada convenient hai.
#benefits:
# efficient storage
# fast loading
# batching
# Hugging Face Trainer/Accelerate compatibility
# dataset metadata/features properly maintained

In [56]:
#Dataset ko disk par save karo
from pathlib import Path

processed_dir = Path("../data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

train_dataset.save_to_disk(
    "../data/processed/alpaca_sft_train"
)

val_dataset.save_to_disk(
    "../data/processed/alpaca_sft_val"
)

print("Processed datasets saved successfully.")

Saving the dataset (1/1 shards): 100%|██████████| 46776/46776 [00:00<00:00, 705907.11 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 5198/5198 [00:00<00:00, 374071.21 examples/s]

Processed datasets saved successfully.

In [57]:
from datasets import load_from_disk

train_check = load_from_disk(
    "../data/processed/alpaca_sft_train"
)

val_check = load_from_disk(
    "../data/processed/alpaca_sft_val"
)

print("Train:", train_check)
print("Validation:", val_check)

print("\nFirst training example:")
print(train_check[0])

Train: Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 46776
})
Validation: Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 5198
})

First training example:
{'input_ids': [4118, 41959, 27, 187, 10987, 271, 5933, 281, 5583, 5098, 281, 10668, 1754, 327, 616, 17971, 15, 187, 187, 4118, 19371, 27, 187, 1145, 5933, 281, 5583, 5098, 281, 10668, 476, 320, 4270, 970, 247, 27549, 19690, 1566, 15, 380, 1566, 3936, 715, 2395, 253, 17503, 326, 4212, 452, 1677, 281, 1798, 5098, 285, 253, 7688, 875, 1027, 2608, 17971, 281, 2794, 247, 625, 3367, 1701, 1984, 17401, 985, 15, 380, 1566, 671, 3936, 715, 2395, 253, 5319, 273, 247, 1984, 13, 824, 347, 697, 19098, 13, 2488, 13, 390, 3727, 3522, 13, 281, 2085, 625, 7899, 12645, 281, 253, 2608, 15], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 1145, 5933, 281, 5583, 5098, 281, 10668, 476, 320, 4270, 970, 247, 27549, 19690, 1566, 15, 380, 1566, 3936, 715, 2395, 253, 17503, 326, 4212, 452, 1677, 281, 1798, 5098, 285, 253, 7688, 875, 1027, 2608, 17971, 281, 2794, 247, 625, 3367, 1701, 1984, 17401, 985, 15, 380, 1566, 671, 3936, 715, 2395, 253, 5319, 273, 247, 1984, 13, 824, 347, 697, 19098, 13, 2488, 13, 390, 3727, 3522, 13, 281, 2085, 625, 7899, 12645, 281, 253, 2608, 15]}

In [ ]:
# Alpaca raw data
#       ↓
# Remove 28 empty responses
#       ↓
# 51,974 examples
#       ↓
# 90/10 split
#       ↓
# 46,776 train
# 5,198 validation
#       ↓
# Prompt + response formatting
#       ↓
# Pythia tokenizer
#       ↓
# MAX_LENGTH = 512
#       ↓
# Tokenization
#       ↓
# Response-only label masking
#       ↓
# Prompt labels = -100
# Response labels = actual token IDs
#       ↓
# HuggingFace Dataset
#       ↓
# Saved to disk



# $$ (x,\; attention\_mask,\; y) $$
# where:

# \(x\) = complete instruction + response tokens
# attention_mask = valid token positions
# \(y\) = response-only training targets